# Generated by Django 2.2 on 2020-09-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0003_auto_20200912_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishes',
            name='granted',
        ),
        migrations.CreateModel(
            name='Granted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wish_granted', models.ManyToManyField(related_name='granted', to='wish_app.Wishes')),
            ],
        ),
    ]
